sudo: false
language: java
jdk:
- oraclejdk8
- oraclejdk7
  firefox: '47.0'
before_install:
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - mvn clean -q
install:
- mvn install -DskipTests=true -q
